### ISSUE TITLE
CSP compatibly

### ISSUE THREAD

**Issue by msteller-connyun** [koala-interactive/frenchkiss.js#12]
I get with frenchkiss a unsafe-eval error, because of a `new function`.

With the current implementation frenchkiss is not CSP compatible.

**Comment by vthibault** [comment]
You are right. Frenchkiss is building optimizing functions by using the `new Function()` command.
There is not much we can do, you'll have to disable the CSP check or switch to another library.

I guess I'll have to document this part in the README.

**Comment by msteller-connyun** [comment]
Disabling CSP is no option. :(
I’m surprised that in the year 2019 are new libraries which are not csp compatible. ;)

However, yes, you should add this to the Readme file. Probably to the checkbox.

**Comment by vthibault** [comment]
Just added a mention at the top of the README.md.
I'll try some tests with pre-compilation of translations at build time to avoid the CSP restrictions :)
