### ISSUE TITLE
[Suggestion] pass params to onMissingKey

### ISSUE THREAD

**Issue by fabien** [koala-interactive/frenchkiss.js#17]
Coming from Polyglot, this would enable the special `_` param to supply the default value.

https://github.com/airbnb/polyglot.js?files=1#polyglotprototypetkey-interpolationoptions

```javascript
let missingKeyHandler = (key, params, lc) => key;
...
missingKeyHandler(key, params, lc);
```

**Comment by vthibault** [comment]
It's now available using the 0.2.0 version.
Thank you for the feedback ! 👍
