### ISSUE TITLE
[Feature Request] Export the getCompiledCode method

### ISSUE THREAD

**Issue by tychenjiajun** [koala-interactive/frenchkiss.js#23]
Or is there any way I can get the compiled `code` and/or `pluralCode` that being the parts of the `new Function` and `compileCode` method?

**Comment by vthibault** [comment]
You can get the compiled function by accessing the generated function inside the cache :

```js
set('en', {
  your_pet:
    'You own {pet, select, dog{a good boy} cat{an evil cat} other{a {pet} ! What is that?}}!',
});

// Call it so it compile the function
t('your_pet', { pet: 'dog' });

// Get compiled function back
const compiledCode = cache.en.your_pet;

// Execute it
const translation = compiledCode(
  { pet:'dog' }, // params
  pluralFn,
  'your pet', // key (only used in missingVariableFn)
  'en', // lang (only used in missingVariableFn)
  missingVariableFn
);
```

It's a not a friendly function as it was only intended to be used internally by the library.
Does it feet your need ?

**Comment by tychenjiajun** [comment]
@vthibault Yes, that's pretty helpful. Thank you!

**Comment by vthibault** [comment]
You're welcome !
