### ISSUE TITLE
[Suggestion] Change the order of parameters

### ISSUE THREAD

**Issue by ftonato** [koala-interactive/frenchkiss.js#5]
Hello,

I think would be interesting to change the order of parameters in the [set](https://github.com/koala-interactive/frenchkiss.js/blob/master/src/frenchkiss.js#L113) function, in this way we can assume that the `language` parameter will receive the default `_locate`, avoiding having to repeat code.

See my suggested code below:
![set-function](https://user-images.githubusercontent.com/5417662/53637257-95b51680-3c1a-11e9-8ca0-34a2d3dcc488.PNG)

Let me know, what do you think about it.

**Comment by vthibault** [comment]
Hi, and thanks for your suggestion !

Apart from the breaking change, I see different problems with this implementation.

If the locale isn't defined, it will do the following :
```js
table[""] = {};
```
I don't feel good with empty string as prop, so it implicates to set a default value to the locale (en ?) to avoid the problem.

It will also break people who wrote the `set()` before the `locale()` thinking there is no internal relations:
```js
set({
  test: 'test',
  // ...
});
locale('xx');
```

And will certainly cause problem with asynchrone JSON loading and `locale()` updates during this time causing the table to be set in the wrong namespace.

My opinion on this one is too keep it verbose to avoid problems.

**Comment by ftonato** [comment]
Hmmm 🤔,

I don't like "verbose" things, but even if we assume a default value to `locale` based on browser language, see the below code, we will have problems with _async_ JSON loading =(

```js
let _locale = !languages[navigator.language]
  ? languages[navigator.language.substr(0, 2).toLowerCase()] ||
    'en',
  : languages[navigator.language];
```

**Comment by vthibault** [comment]
In my opinion, it's not up to this library to check the user language. All websites have different rules to determine it, and the browser language is most of the time the last verification they do, in the order :
- hl query parameter.
- fb_locale query parameter.
- account language (session, cookie)
- language folder in the url
- language dns the url
- browser language

If you really want something that doesn't lead to errors and don't duplicate commands it will be better to configure the table and the locale at the same time, only one function needed.

Something like _(not implemented)_ :
```js
frenchkiss.init({
  locale: 'en',
  fallback: 'fr',
  messages: {
    en: {
       test: 'test'
    },
    fr: {
       test: 'test'
    };
  }
});
```

**Comment by ftonato** [comment]
Yeah, I agree with you:
> it's not up to this library to check the user language 👍 

`let maybe? = 'keep it verbose is the best approach to avoid problems.';`

![index](https://user-images.githubusercontent.com/5417662/53651261-2b15d200-3c3e-11e9-9dc9-a23c6e8339ae.jpg)
